MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "RegionProposalNetwork"
  PROPOSAL_GENERATOR:
    NAME: MyRPN
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: MyRes5ROIHeads
VIS_PERIOD: 0
OUTPUT_DIR: "/home/mtarantino/thesis/oursowod/out/baseline/step1/train" # path to store the result
DATASETS:
  TRAIN: ("VOC2007_all",)
SOLVER:
  MAX_ITER: 40000
  STEPS: (30000,)
OURS:
  MODE: "baseline"
  STEP: 1
  DATASETS:
    ROOT_DIR: "/home/mtarantino/thesis/oursowod/data"
    INFO:
      NAME: "VOC2007"
      YEAR: 2007
      SUBDIR: "pascal-voc/VOC2007/trainval"
      SPLIT: "trainval"
  WRITERS:
    PERIOD: 20
  CHECKPOINT_DIR : "/home/mtarantino/thesis/oursowod/checkpoint/baseline/step1/train" # path to store the checkpoint
