MODEL:
  WEIGHTS: "/home/mtarantino/thesis/oursowod/checkpoint/baseline/step1/train/model_final.pth"
  META_ARCHITECTURE: "RegionProposalNetwork"
  BACKBONE:
    FREEZE_AT: 2
  PROPOSAL_GENERATOR:
    NAME: MyRPN
  ROI_HEADS:
    NUM_CLASSES: 20
    NAME: MyRes5ROIHeads
VIS_PERIOD: 0
OUTPUT_DIR: "/home/mtarantino/thesis/oursowod/out/ours/one_std/noreg/step3/train" # path to store the result
DATASETS:
  TRAIN: ("VOC2007_all",)
SOLVER:
  MAX_ITER: 10000
  STEPS: (7500, )
OURS:
  STEP: 3
  FREEZE_AT: 5
  MODELS:
    RCNN:
      WEIGHTS: "/home/mtarantino/thesis/oursowod/checkpoint/ours/one_std/noreg/step2/train/model_final.pth"
  DATASETS:
    ROOT_DIR: "/home/mtarantino/thesis/oursowod/data"
    INFO:
      NAME: "VOC2007"
      YEAR: 2007
      SUBDIR: "pascal-voc/VOC2007"
      SPLIT: "trainval"
  WRITERS:
    PERIOD: 20
  CHECKPOINT_DIR: "/home/mtarantino/thesis/oursowod/checkpoint/ours/one_std/noreg/step3/train" # path to store the checkpoint
  CHECKPOINT_DIR_RCNN: "/home/mtarantino/thesis/oursowod/checkpoint/ours/one_std/noreg/step2/train"
